services:
  mariadb:
    image: mariadb:11
    container_name: tododb
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: todoapp
      MYSQL_USER: todo
      MYSQL_PASSWORD: todopw
    ports:
      - "3306:3306"
    volumes:
      - mariadb-data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mariadb-data:k